-- Create the table for user profiles
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  date_of_birth DATE,
  unlocked BOOLEAN DEFAULT false,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable Row Level Security for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Add RLS policies for profiles
CREATE POLICY "Users can view their own profile."
ON public.profiles FOR SELECT
USING (auth.uid() = id);

CREATE POLICY "Users can create their own profile."
ON public.profiles FOR INSERT
WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile."
ON public.profiles FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- Create numerology_interpretations table
CREATE TABLE public.numerology_interpretations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INT NOT NULL,
    type VARCHAR(255) NOT NULL,
    title TEXT,
    description TEXT,
    interpretation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable Row Level Security for interpretations
ALTER TABLE public.numerology_interpretations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to interpretations"
ON public.numerology_interpretations
FOR SELECT USING (true);


-- Refactored Interpretations Seeding
-- Seed Life Path Numbers 1-9 and Master Numbers 11, 22, 33
INSERT INTO public.numerology_interpretations (number, type, title, description, interpretation) VALUES
(1, 'Life Path', 'The Leader', 'Innovative, independent, and a trailblazer.', '...'),
(2, 'Life Path', 'The Cooperator', 'Diplomatic, sensitive, and a team player.', '...'),
(3, 'Life Path', 'The Communicator', 'Creative, expressive, and joyful.', '...'),
(4, 'Life Path', 'The Builder', 'Practical, organized, and hardworking.', '...'),
(5, 'Life Path', 'The Adventurer', 'Freedom-loving, versatile, and dynamic.', '...'),
(6, 'Life Path', 'The Nurturer', 'Responsible, loving, and community-oriented.', '...'),
(7, 'Life Path', 'The Seeker', 'Analytical, spiritual, and introspective.', '...'),
(8, 'Life Path', 'The Powerhouse', 'Ambitious, authoritative, and successful.', '...'),
(9, 'Life Path', 'The Humanitarian', 'Compassionate, idealistic, and selfless.', '...'),
(11, 'Life Path', 'The Intuitive', 'Visionary, insightful, and spiritually aware.', '...'),
(22, 'Life Path', 'The Master Builder', 'Powerful, practical, and a world-changer.', '...'),
(33, 'Life Path', 'The Master Teacher', 'Nurturing, compassionate, and a spiritual guide.', '...'); 